language: node_js

sudo: false

node_js:
  - "12"

services: mongodb

install:
  - mongod --version
  - npm install

script:
  - npm run test-cov

after_script:
  - cat ./coverage/lcov.info | coveralls
