language: node_js

sudo: false

env:
  - CXX=g++-4.8

node_js:
  - "6"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
  - $CXX --version

install: true

services: mongodb

script:
  - npm install
  - npm run travis-test
